### ISSUE TITLE
Add production build command

### ISSUE THREAD

**Issue by lorensr** [tmeasday/create-graphql-server#54]
`npm run build` since `babel-node` isn't meant for production use. My attempt is failing:

```
$ GLOBIGNORE="node_modules/*"; babel -o build.js index.js **/*.js
ReferenceError: [BABEL] index.js: Unknown option: /Users/me/gh/api-model/node_modules/babel-preset-env/lib/index.js.__esModule. Check out http://babeljs.io/docs/usage/options/ for more info
    at Logger.error (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:267:20)
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.addConfig (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
```

**Comment by tmeasday** [comment]
We use this:

```
babel . -d dist --copy-files
```
